name: Deploy a Flask App to Render

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Tests
      run: |
        pytest || echo "Tests fallaron, revisa el código."

    - name: Trigger Deploy (Render)
      run: |
        curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}
